version: 0.0.{build}

branches:
  only:
  - ci

build:
  verbosity: minimal

matrix:
  fast_finish: true

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      RID: win-x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      RID: linux-x64
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      RID: osx-x64

build_script:
- ps: cd ./engine/Bomberjam
- ps: pwd
- ps: dotnet restore
- ps: pwd
- ps: dotnet publish -c Release -r $env:RID -o ./dist/engine/$env:RID

artifacts:
  - path: ./engine/Bomberjam/dist
    name: engine